//%attributes = {"invisible":true,"preemptive":"capable"}
// OnErr_GetLastError () : errorNo
// 
// DESCRIPTION
//   Returns the error that was generated by
//   OnErr_GENERIC
//
C_LONGINT:C283($0; gError)
// ----------------------------------------------------

$0:=gError