//%attributes = {"invisible":true,"preemptive":"capable"}
// OnErr_GetLastError () : errorNo
// 
// DESCRIPTION
//   Returns the error that was generated by
//   OnErr_GENERIC
//
#DECLARE() : Integer
// ----------------------------------------------------

var gError : Integer
return gError